# SilverStripe\SiteConfig\SiteConfig:
#   extensions:
#     - NZTA\SiteBanner\Extensions\SiteConfigExtension
# NZTA\SiteBanner\Models\SiteBanner:
#   required_permission_codes:
#     - ADMIN
#   banner_types: [identifier: title]
#   embargo_enabled: true
